<a href="https://colab.research.google.com/github/madhansree005-coder/climatescope-project/blob/data-cleaning/Climatescope%20milestone%201%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("GlobalWeatherRepository.csv")

In [8]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.400,26.600,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.100,2.000,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.400,18.400,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.700,0.900,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.400,262.300,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97430,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1759131900,2025-09-29 03:45,25.1,77.2,Clear,...,18.870,23.310,2,2,06:16 AM,06:19 PM,12:32 PM,No moonset,First Quarter,42
97431,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1759131900,2025-09-29 14:45,26.4,79.5,Moderate or heavy rain with thunder,...,9.065,9.620,1,1,05:47 AM,05:47 PM,12:02 PM,10:46 PM,Waxing Crescent,38
97432,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1759131900,2025-09-29 10:45,21.7,71.0,Sunny,...,26.825,56.055,2,3,05:53 AM,05:54 PM,12:03 PM,11:17 PM,Waxing Crescent,39
97433,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1759131900,2025-09-29 09:45,29.8,85.6,Sunny,...,24.050,24.790,2,3,05:51 AM,06:03 PM,10:57 AM,No moonset,First Quarter,40
97434,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1759131900,2025-09-29 09:45,26.1,78.9,Sunny,...,28.490,29.785,2,3,05:40 AM,05:53 PM,10:40 AM,No moonset,First Quarter,40

In [9]:
import os
import pandas as pd

In [10]:
print("Working dir:", os.getcwd())
print("Files here:", os.listdir('.')[:20])

Working dir: /content
Files here: ['.config', 'GlobalWeatherRepository.csv', 'sample_data']

In [11]:
paths = [
    "GlobalWeatherRepository.csv"
]

csv_path = None
for p in paths:
    if os.path.exists(p):
        csv_path = p
        break

if csv_path is None:
    raise FileNotFoundError("CSV not found. Upload the file to Colab or set the correct path.")

In [12]:
df = pd.read_csv(csv_path)

In [13]:
df.columns = df.columns.str.strip()
print("Column names (first 20):", df.columns.tolist()[:20])

Column names (first 20): ['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud']

In [14]:
first_col = df.columns[0]
print("\nFirst column name:", first_col)
print(df[first_col].head())

if 'country' in df.columns:
    print("\n'country' column head:")
    print(df['country'].head())
else:
    print("\nNo column named 'country' exactly — check the printed column list above.")

First column name: country
0    Afghanistan
1        Albania
2        Algeria
3        Andorra
4         Angola
Name: country, dtype: object

'country' column head:
0    Afghanistan
1        Albania
2        Algeria
3        Andorra
4         Angola
Name: country, dtype: object

In [15]:
df = pd.read_csv('GlobalWeatherRepository.csv')
print(df['country'].head())

0    Afghanistan
1        Albania
2        Algeria
3        Andorra
4         Angola
Name: country, dtype: object

In [16]:
import pandas as pd

df = pd.read_csv("GlobalWeatherRepository.csv")

print("Dataset shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nQuick summary:")
print(df.info())
print("\nSample rows:")
print(df.head())

Dataset shape: (97435, 41)

Column names: ['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']

Data types:
country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                     float64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                float64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

Quick summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97435 entries, 0 to 97434
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       97435 non-null  object
 1   location_name                 97435 non-null  object
 2   latitude                      97435 non-null  float64
 3   longitude                     97435 non-null  float64
 4   timezone                      97435 non-null  object
 5   last_updated_epoch            97435 non-null  int64
 6   last_updated                  97435 non-null  object
 7   temperature_celsius           97435 non-null  float64
 8   temperature_fahrenheit        97435 non-null  float64
 9   condition_text                97435 non-null  object
 10  wind_mph                      97435 non-null  float64
 11  wind_kph                      97435 non-null  float64
 12  wind_degree                   97435 non-null  int64
 13  wind_direction                97435 non-null  object
 14  pressure_mb                   97435 non-null  float64
 15  pressure_in                   97435 non-null  float64
 16  precip_mm                     97435 non-null  float64
 17  precip_in                     97435 non-null  float64
 18  humidity                      97435 non-null  int64
 19  cloud                         97435 non-null  int64
 20  feels_like_celsius            97435 non-null  float64
 21  feels_like_fahrenheit         97435 non-null  float64
 22  visibility_km                 97435 non-null  float64
 23  visibility_miles              97435 non-null  float64
 24  uv_index                      97435 non-null  float64
 25  gust_mph                      97435 non-null  float64
 26  gust_kph                      97435 non-null  float64
 27  air_quality_Carbon_Monoxide   97435 non-null  float64
 28  air_quality_Ozone             97435 non-null  float64
 29  air_quality_Nitrogen_dioxide  97435 non-null  float64
 30  air_quality_Sulphur_dioxide   97435 non-null  float64
 31  air_quality_PM2.5             97435 non-null  float64
 32  air_quality_PM10              97435 non-null  float64
 33  air_quality_us-epa-index      97435 non-null  int64
 34  air_quality_gb-defra-index    97435 non-null  int64
 35  sunrise                       97435 non-null  object
 36  sunset                        97435 non-null  object
 37  moonrise                      97435 non-null  object
 38  moonset                       97435 non-null  object
 39  moon_phase                    97435 non-null  object
 40  moon_illumination             97435 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 30.5+ MB
None

Sample rows:
       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch      last_updated  temperature_celsius  \
0          1715849100  2024-05-16 13:15                 26.6
1          1715849100  2024-05-16 10:45                 19.0
2          1715849100  2024-05-16 09:45                 23.0
3          1715849100  2024-05-16 10:45                  6.3
4          1715849100  2024-05-16 09:45                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                    79.8  Partly Cloudy  ...                8.4
1                    66.2  Partly cloudy  ...                1.1
2                    73.4          Sunny  ...               10.4
3                    43.3  Light drizzle  ...                0.7
4                    78.8  Partly cloudy  ...              183.4

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0              26.6                         1                          1
1               2.0                         1                          1
2              18.4                         1                          1
3               0.9                         1                          1
4             262.3                         5                         10

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous                 55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous                 55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous                 55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous                 55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous                 55

[5 rows x 41 columns]

In [17]:
missing_summary = df.isnull().sum().sort_values(ascending=False)
print("\nMissing values per column:\n", missing_summary)

Missing values per column:
 country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [18]:
print("\nNumber of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [19]:
print("\nSummary stats:")
print(df.describe(include="all"))

Summary stats:
         country location_name      latitude     longitude      timezone  \
count      97435         97435  97435.000000  97435.000000         97435
unique       211           254           NaN           NaN           197
top     Bulgaria         Kabul           NaN           NaN  Asia/Bangkok
freq        1069           501           NaN           NaN          1911
mean         NaN           NaN     19.146115     22.112882           NaN
std          NaN           NaN     24.457297     65.819599           NaN
min          NaN           NaN    -41.300000   -175.200000           NaN
25%          NaN           NaN      3.750000     -6.836100           NaN
50%          NaN           NaN     17.250000     23.316700           NaN
75%          NaN           NaN     40.400000     50.580000           NaN
max          NaN           NaN     64.150000    179.220000           NaN

        last_updated_epoch      last_updated  temperature_celsius  \
count         9.743500e+04             97435         97435.000000
unique                 NaN             16545                  NaN
top                    NaN  2025-04-18 11:15                  NaN
freq                   NaN                44                  NaN
mean          1.737542e+09               NaN            22.788837
std           1.252229e+07               NaN             8.893859
min           1.715849e+09               NaN           -24.900000
25%           1.726743e+09               NaN            18.100000
50%           1.737541e+09               NaN            25.000000
75%           1.748422e+09               NaN            28.300000
max           1.759132e+09               NaN            49.200000

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
count             97435.000000          97435  ...       97435.000000
unique                     NaN             47  ...                NaN
top                        NaN  Partly cloudy  ...                NaN
freq                       NaN          30385  ...                NaN
mean                 73.021634            NaN  ...          26.167342
std                  16.008748            NaN  ...          40.829209
min                 -12.800000            NaN  ...           0.168000
25%                  64.600000            NaN  ...           7.400000
50%                  77.000000            NaN  ...          15.170000
75%                  82.900000            NaN  ...          29.970000
max                 120.600000            NaN  ...        1614.100000

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
count       97435.000000              97435.000000               97435.000000
unique               NaN                       NaN                        NaN
top                  NaN                       NaN                        NaN
freq                 NaN                       NaN                        NaN
mean           53.765763                  1.760979                   2.762200
std           164.167510                  0.981699                   2.567807
min         -1848.150000                  1.000000                   1.000000
25%            10.900000                  1.000000                   1.000000
50%            22.200000                  1.000000                   2.000000
75%            46.065000                  2.000000                   3.000000
max          6037.290000                  6.000000                  10.000000

         sunrise    sunset     moonrise     moonset       moon_phase  \
count      97435     97435        97435       97435            97435
unique       458       544         1441        1441                8
top     05:57 AM  06:28 PM  No moonrise  No moonset  Waxing Crescent
freq        1086       934         3302        3171            21623
mean         NaN       NaN          NaN         NaN              NaN
std          NaN       NaN          NaN         NaN              NaN
min          NaN       NaN          NaN         NaN              NaN
25%          NaN       NaN          NaN         NaN              NaN
50%          NaN       NaN          NaN         NaN              NaN
75%          NaN       NaN          NaN         NaN              NaN
max          NaN       NaN          NaN         NaN              NaN

        moon_illumination
count        97435.000000
unique                NaN
top                   NaN
freq                  NaN
mean            49.699636
std             35.089898
min              0.000000
25%             15.000000
50%             50.000000
75%             85.000000
max            100.000000

[11 rows x 41 columns]

In [20]:
import numpy as np

for col in df.columns:
    if df[col].dtype in [np.float64, np.int64]:
        df[col].fillna(df[col].mean(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)


df.drop_duplicates(inplace=True)

/tmp/ipython-input-2682978523.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-2682978523.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [21]:
if 'temperature_F' in df.columns:
    df['temperature_C'] = (df['temperature_F'] - 32) * 5/9

In [22]:
if 'precipitation_mm' in df.columns:
    df['precipitation_cm'] = df['precipitation_mm'] / 10

In [23]:
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = (df[numeric_cols] - df[numeric_cols].min()) / (df[numeric_cols].max() - df[numeric_cols].min())

In [24]:
if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], errors='coerce')

    # Group by year-month
    monthly_avg = df.groupby(df['date'].dt.to_period("M")).mean(numeric_only=True)
    monthly_avg = monthly_avg.reset_index()

    print("\nMonthly average sample:\n", monthly_avg.head())

In [25]:
df = pd.read_csv("GlobalWeatherRepository.csv")

df['last_updated'] = pd.to_datetime(df['last_updated'], errors='coerce')


df = df.dropna(subset=['last_updated'])


df.set_index('last_updated', inplace=True)


monthly_avg = df.resample('M').mean(numeric_only=True)


monthly_avg = monthly_avg.reset_index()


print(monthly_avg.head())

  last_updated   latitude  longitude  last_updated_epoch  temperature_celsius  \
0   2024-05-31  19.330079  21.252653        1.716476e+09            25.153214
1   2024-06-30  19.169585  21.786945        1.718494e+09            26.456036
2   2024-07-31  19.090607  22.195843        1.721096e+09            26.800448
3   2024-08-31  19.107315  22.088584        1.723808e+09            26.789677
4   2024-09-30  19.064397  22.147510        1.726441e+09            25.124402

   temperature_fahrenheit  wind_mph   wind_kph  wind_degree  pressure_mb  ...  \
0               77.275500  8.897635  14.322680   170.234384  1013.072468  ...
1               79.622507  9.127415  14.694197   178.421044  1011.961081  ...
2               80.242645  8.684089  13.979538   183.502419  1011.521233  ...
3               80.223093  8.643540  13.915649   180.594045  1011.993052  ...
4               77.226417  8.222507  13.235980   169.814720  1013.014173  ...

    gust_kph  air_quality_Carbon_Monoxide  air_quality_Ozone  \
0  22.285567                   527.585263          60.698423
1  22.217324                   501.149371          63.579353
2  20.857391                   446.389697          65.601846
3  20.407428                   438.953069          67.023672
4  18.974658                   407.732131          70.947643

   air_quality_Nitrogen_dioxide  air_quality_Sulphur_dioxide  \
0                     10.185324                     6.788720
1                      9.038798                     6.582004
2                      8.044042                     4.098208
3                      8.006352                     5.857237
4                     10.442420                     9.618837

   air_quality_PM2.5  air_quality_PM10  air_quality_us-epa-index  \
0          17.821771         33.466252                  1.391146
1          16.837369         30.644171                  1.358016
2          15.947017         28.087225                  1.318043
3          14.332291         24.084119                  1.310835
4          20.946278         44.547416                  1.618852

   air_quality_gb-defra-index  moon_illumination
0                    1.850819          78.780776
1                    1.788359          49.536077
2                    1.712955          43.570865
3                    1.720430          45.561125
4                    2.353654          46.063525

[5 rows x 31 columns]

/tmp/ipython-input-237631861.py:12: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = df.resample('M').mean(numeric_only=True)

In [26]:
import pandas as pd
import numpy as np


df = pd.read_csv("GlobalWeatherRepository.csv")


print("Columns in dataset:\n", df.columns.tolist())


if 'temperature_F' in df.columns:
    df['temperature_C'] = (df['temperature_F'] - 32) * 5/9
    print("\n✅ Converted 'temperature_F' to 'temperature_C'")


if 'precipitation_mm' in df.columns:
    df['precipitation_cm'] = df['precipitation_mm'] / 10
    print("✅ Converted 'precipitation_mm' to 'precipitation_cm'")


if 'wind_speed_kmh' in df.columns:
    df['wind_speed_ms'] = df['wind_speed_kmh'] / 3.6
    print("✅ Converted 'wind_speed_kmh' to 'wind_speed_ms'")


numeric_cols = df.select_dtypes(include=[np.number]).columns


df_normalized = df.copy()
df_normalized[numeric_cols] = (
    df[numeric_cols] - df[numeric_cols].min()
) / (df[numeric_cols].max() - df[numeric_cols].min())

print("\n✅ Numeric values normalized (range 0–1)")


print("\nConverted and normalized data preview:")
print(df_normalized.head())

Columns in dataset:
 ['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']

✅ Numeric values normalized (range 0–1)

Converted and normalized data preview:
       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul  0.719014   0.689521      Asia/Kabul
1      Albania            Tirana  0.783594   0.550251   Europe/Tirane
2      Algeria           Algiers  0.740256   0.502934  Africa/Algiers
3      Andorra  Andorra La Vella  0.794689   0.498617  Europe/Andorra
4       Angola            Luanda  0.307824   0.531657   Africa/Luanda

   last_updated_epoch      last_updated  temperature_celsius  \
0                 0.0  2024-05-16 13:15             0.695007
1                 0.0  2024-05-16 10:45             0.592443
2                 0.0  2024-05-16 09:45             0.646424
3                 0.0  2024-05-16 10:45             0.421053
4                 0.0  2024-05-16 09:45             0.686910

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                0.694153  Partly Cloudy  ...           0.005101
1                0.592204  Partly cloudy  ...           0.000577
2                0.646177          Sunny  ...           0.006340
3                0.420540  Light drizzle  ...           0.000330
4                0.686657  Partly cloudy  ...           0.113531

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0          0.237748                       0.0                        0.0
1          0.234629                       0.0                        0.0
2          0.236708                       0.0                        0.0
3          0.234489                       0.0                        0.0
4          0.267639                       0.8                        1.0

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous               0.55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous               0.55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous               0.55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous               0.55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous               0.55

[5 rows x 41 columns]